### ISSUE TITLE
warning: possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by wynfrith** [DigitalIO/koajs-nunjucks#1]
I am getting following warning:
```javascript
(node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:239:17)
    at Object.fs.watchFile (fs.js:1340:8)
    at EventEmitter.FSWatcher._watch (/home/wyn/Documents/TestPool/koa/node_modules/koajs-nunjucks/node_modules/nunjucks/node_modules/chokidar/index.js:251:8)
    at EventEmitter.FSWatcher._handleDir (/home/wyn/Documents/TestPool/koa/node_modules/koajs-nunjucks/node_modules/nunjucks/node_modules/chokidar/index.js:351:8)
    at /home/wyn/Documents/TestPool/koa/node_modules/koajs-nunjucks/node_modules/nunjucks/node_modules/chokidar/index.js:385:38
    at FSReqWrap.oncomplete (fs.js:82:15)

```

I used the nodejs@0.12.7 and this is my code:

```javascript
var koa = require('koa');
var morgan = require('koa-morgan');
var nunjucks = require('koajs-nunjucks');
var etag = require('koa-etag');
var fresh = require('koa-fresh');
var app = koa();

app.use(morgan.middleware('dev'));

app.use(fresh());
app.use(etag());
//
app.use(nunjucks('views',{autoescape:true}));


app.use(function *(next) {
    this.body = 'hello world';
});

app.listen(3000);
```

**Comment by elfet** [comment]
Me too! :+1:

**Comment by wynfrith** [comment]
@elfet you can use [koa-nunjucks-2](https://github.com/strawbrary/koa-nunjucks-2) or [koa-views](https://github.com/queckezz/koa-views)

**Comment by elfet** [comment]
Found better solution: my own miggleware:
```js
"use strict";
let nunjucks = require('nunjucks');

module.exports = (path, opts) => function *(next) {
  this.nunjucks = nunjucks.configure(path, opts);
  let self = this;

  this.render = function* render(name, context) {
    self.body = yield new Promise((resolve, reject) => {
      self.nunjucks.render(name, context,
        function (err, res) {
          if (err) {
            reject(err);
          } else {
            resolve(res);
          }
        }
      );
    });
  };

  yield next;
};
```
